name: Backend deploy
on:
  workflow_dispatch:
jobs:
    configure-kubectl:
        runs-on: self-hosted
        environment:
            name: development
        steps:
            - name: Set up kubectl
              uses: azure/setup-kubectl@v4
            - name: Configure kubeconfig
              uses: azure/k8s-set-context@v4
              with:
                 method: kubeconfig
                 kubeconfig: ${{ secrets.KUBECONFIG }}
            - name: Test connection
              run: kubectl config current-context

        

    