on:
  workflow_dispatch:
  push:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [x64, arm64]
      fail-fast: false
    container:
      image: gradle:8.5-jdk21
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build without testing
        run: gradle build -x test
        
      - name: Caching Gradle dependencies after build
        uses: actions/cache/save@v4
        with:
          path: |
            .gradle
            build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

  unit-test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        architecture: [x64, arm64]
      fail-fast: false
    container:
      image: gradle:8.5-jdk21
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Cache Gradle dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            .gradle
            build
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Check Java and Gradle Version
        run: |
          java --version
          gradle --version
          
      - name: Unit Test
        run: gradle test

  
  
      
  

