name: Backend deploy
on:
  workflow_dispatch:
jobs:
    configure-kubectl:
        runs-on: self-hosted
        environment:
            name: development
        steps:
            - name: Set up kubectl
              uses: azure/setup-kubectl@v4
            - name: Set up kubeconfig 
              run: |
               echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
               chmod 600 $HOME/.kube/config
            - name: Test connection
              run: kubectl get nodes
        

    